name: kinodata
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - requests
  - tqdm
  - chembl_webresource_client
  - pandas
  - matplotlib-base
  - xlrd
  - beautifulsoup4
  - ipympl
  - pip:
    - venn
