name: openkinome-datascripts
channels:
  - conda-forge
packages:
  - python
  - pip
  - requests
  - tqdm
  - chembl_webresource_client
  - pandas
  - matplotlib-base
  - xlrd
  - beautifulsoup4
pip:
  - venn
